name: pre-commit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
    pre-commit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.10
          uses: actions/setup-python@v1
          with:
            python-version: 3.10.7
        - name: Install pipenv
          uses: dschep/install-pipenv-action@v1
        - name: Run tests
          run: |
            pipenv install --dev
            pipenv run "pre-commit run -a"