name: pre-commit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
    pre-commit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.10
          uses: actions/setup-python@v1
          with:
            python-version: 3.10.7
        - name: install pre-commit
          run: |
            pip install pre-commit
        - name: pre-commit-hook
          run: |
            pre-commit run --all-files