name: pre-commit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
    pre-commit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          uses: VaultVulp/action-pipenv@v2.0.1
          with:
            command: install -d # Install all dependencies, including development ones
        - name: run-pre-commit
          run: |
            pre-commit run -a