name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

#jobs:
#  pre-commit:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - uses: actions/setup-python@v3
#    - uses: pre-commit/action@v3.0.0

jobs:
    pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: install python dependencies
        run: |
          pipenv install
      - name: Linting
        run: |
          pre-commit run -a
